const Images = {
  Splash: require('./icon/Splash.jpg'),
  backgroundImage: require('./icon/backgroundImage.png'),

  hederLogo: require('./icon/appLogo.png'),
  bell: require('./icon/bell.png'),
  search: require('./icon/search.png'),
  email: require('./icon/email.png'),
  password: require('./icon/password.png'),
  showPassword: require('./icon/showpassword.png'),
  google: require('./icon/Google.png'),
  twitter: require('./icon/Twitter.png'),

  homeLogo: require('./icon/homeLogo.png'),
  addLogo: require('./icon/addLogo.png'),
  msgLogo: require('./icon/msgLogo.png'),
  profileLogo: require('./icon/profileLogo.png'),
  bottamArrow: require('./icon/bottamArrow.png'),
  menu: require('./icon/Menu.png'),

  plus: require('./icon/plus.png'),
  lock: require('./icon/lock.png'),
  profile: require('./icon/profile.png'),
  gallery: require('./icon/gallery.png'),
  Vector: require('./icon/Vector.png'),
  edit: require('./icon/edit.png'),
  Menu: require('./icon/Menu.png'),
  threedots: require('./icon/threedots.png'),
  Mask: require('./icon/Mask.png'),
  favorit: require('./icon/favorit.png'),
  dislike: require('./icon/dislike.png'),
  comments: require('./icon/comments.png'),
  share: require('./icon/share.png'),
  dot: require('./icon/dot.png'),
  onedot: require('./icon/onedot.png'),
  Mask2: require('./icon/Mask2.png'),
  Mask3: require('./icon/Mask3.png'),
  Mask4: require('./icon/Mask4.png'),

  Rightarrow: require('./icon/Rightarrow.png'),
  like: require('./icon/like.png'),

  RightIcon: require('./icon/RightIcon.png'),
  TreehLine: require('./icon/TreehLine.png'),
  Setting: require('./icon/Setting.png'),
  Cards: require('./icon/Cards.png'),
  Addbank: require('./icon/Addbank.png'),
  HelfIcon: require('./icon/HelfIcon.png'),
  DarkActive: require('./icon/DarkActive.png'),
  enlishIcon: require('./icon/enlishIcon.png'),
  profileIcon: require('./icon/profileIcon.png'),
  mainimg: require('./icon/mainimg.png'),
  profile: require('./icon/profile.png'),
  icon1: require('./icon/icon1.png'),
  icon2: require('./icon/icon2.png'),
  img1: require('./icon/img1.png'),
  img2: require('./icon/img2.png'),
  img3: require('./icon/img3.png'),
  dot: require('./icon/dot.png'),
  mainboyimg: require('./icon/mainboyimg.png'),
  boyimg1: require('./icon/boyimg1.png'),
  boyimg2: require('./icon/boyimg2.png'),
  boyimg3: require('./icon/boyimg3.png'),
  play: require('./icon/play.png'),
  likeicon: require('./icon/likeicon.png'),
  coment: require('./icon/coment.png'),
  share: require('./icon/share.png'),
  camera: require('./icon/camera.png'),
  girlimg: require('./icon/girlimg.png'),
  profileimg: require('./icon/profileimg.png'),
  delete: require('./icon/delete.png'),
  eyeimg: require('./icon/eyeimg.png'),
  chatgirlimg: require('./icon/chatgirlimg.png'),
  Plus: require('./icon/plus.png'),
  lock: require('./icon/lock.png'),
  logout: require('./icon/logout.png'),
  bgcamera: require('./icon/bgcamera.png'),
  eye: require('./icon/eye.png'),
};
export default Images;
